name: electron-packager-hello-world-sandbox
version: '0.1'
summary: Hello World Electron app
description: |
  Simple Hello World Electron app as an example
base: core18
confinement: strict
grade: stable

plugs:
  browser-sandbox:
    interface: browser-support
    allow-sandbox: true
    
apps:
  electron-packager-hello-world-sandbox:
    command: electron-quick-start/electron-quick-start
    extensions: [gnome-3-34]
    plugs:
    - browser-support
    - network
    - network-bind
    - pulseaudio

parts:
  electron-quick-start:
    plugin: nil
    source: https://github.com/electron/electron-quick-start.git
    override-build: |
        npm install electron electron-packager
        ./node_modules/.bin/electron-packager . --overwrite --platform=linux --output=release-build --prune=true
        cp -rv ./electron-quick-start-linux-* $SNAPCRAFT_PART_INSTALL/electron-quick-start
    build-snaps:
    - node/14/stable
    build-packages:
    - unzip
    stage-packages:
    - libnss3
    - libnspr4
