name: electron-kiosk
version: '0.1'
summary: Hello World Electron app for a Kiosk
description: |
  Simple Hello World Electron app as an example HTML5 Kiosk
base: core18
confinement: strict
grade: stable

apps:
  electron-kiosk:
    command: electron-quick-start/electron-quick-start --no-sandbox
    extensions: [gnome-3-28]
    plugs:
    - browser-support
    - network
    - network-bind

  daemon:
    daemon: simple
    restart-condition: always
    command:  electron-quick-start/electron-quick-start --no-sandbox
    command-chain: [bin/xwayland-kiosk-launch]
    extensions: [gnome-3-28]
    plugs:
    - browser-support
    - network
    - network-bind

environment:
  XWAYLAND_FULLSCREEN_WINDOW_HINT: window_role="browser-window"

parts:
  electron-quick-start:
    plugin: nil
    source: https://github.com/electron/electron-quick-start.git
    override-build: |
        npm install electron electron-packager
        ./node_modules/.bin/electron-packager . --overwrite --platform=linux --output=release-build --prune=true
        cp -rv ./electron-quick-start-linux-* $SNAPCRAFT_PART_INSTALL/electron-quick-start
    build-snaps:
    - node/14/stable
    build-packages:
    - unzip
    stage-packages:
    - libnss3
    - libnspr4

  xwayland-kiosk-helper:
    plugin: cmake
    source: https://github.com/MirServer/xwayland-kiosk-helper.git
    override-build: |
      snapcraftctl build
      sed -i 's|^"$@"$|exec "$@"|g' $SNAPCRAFT_PART_INSTALL/bin/xwayland-kiosk-launch
    build-packages:
      - build-essential
    stage-packages:
      - i3
      - libegl1-mesa
      - libgl1-mesa-glx
      - xwayland
